# Generated by Django 5.1.1 on 2024-11-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_customuser_role_alter_customuser_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("student", "Student"),
                    ("teacher", "Teacher"),
                ],
                default="student",
                max_length=10,
            ),
        ),
    ]
